name: Soul Venture Travel Collective
favicon: null
layout_spectrum: 0.75249
typography_spectrum: 0.04545575939118862
title: Soul Venture Travel Collective
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c7773'
    - '#524d49'
    - '#c9c4c0'
    - '#0d0805'
    - '#7d3112'
  brandStrength: 0.3125
  lightness: 0.29592813621275127
  saturation: 0.3512043484952301
  rhythmicContrast: 0.4923085104674101
purpose: []
